---
  - name: Install packages
    become: yes
    become_user: root
    become_method: sudo
    apt: name={{ item }} state=installed update_cache=yes
    with_items:
      # Dependencies
      - git
      - irssi
      - supervisor
      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv
