- name: restart miniircd
  # supervisorctl module is a bit junky, doesn't support rereading configs yet
  # So I just force the command
  become: yes
  become_user: root
  become_method: sudo
  command: /usr/bin/supervisorctl -c /etc/supervisor/supervisord.conf restart miniircd

- name: vboxfs pyborg.cfg workaround
  command: cp /tmp/pyborg.cfg {{ borgnana_dest }}/pyborg.cfg
  notify: restart borgnana

- name: vboxfs pyborg-irc.cfg workaround
  command: cp /tmp/pyborg-irc.cfg {{ borgnana_dest }}/pyborg-irc.cfg
  notify: restart borgnana

- name: restart borgnana
  # supervisorctl module is a bit junky, doesn't support rereading configs yet
  # So I just force the command
  become: yes
  become_user: root
  become_method: sudo
  command: /usr/bin/supervisorctl -c /etc/supervisor/supervisord.conf restart borgnana
